config/routes.rb
Kindsy::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :dashboards, :nursery_groups, :nurseries, :currencies, :rooms, :open_hours, :periods, :period_prices, :billing_periods, :presets, :discounts, :local_authorities, :terms

  resources :carers do
    member do
      get 'detail'
      get 'relationships'
      put 'remove_relationship'
      get 'search_children' 
      put 'add_children'
      put 'assign_accounts'
      get 'search_accounts'          
    end
  end 
  
  resources :accounts do
    member do
      get 'related_children'
      put 'remove_child'
      get 'search_children'
      put 'add_children'
      get 'related_carers'
      get 'search_carers'
      put 'add_carers'
      put 'remove_carer'
    end
  end
  
  resources :children do
    member do
      get 'detail'
    end
    resources :bookings
    resources :timesheets
  end
  
  resources :invoices do
    resources :invoice_line_items
  end
  
  get "static_pages/home"
  

  devise_for :users, :controllers => {:registrations => "registrations"}


  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  
  match '/static_pages_home' => "static_pages#home", as: :user_root


 
end

app/models/currency.rb
# == Schema Information
#
# Table name: currencies
#
#  id               :integer         not null, primary key
#  currency_type_id :integer
#  nursery_id       :integer
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#

class Currency < ActiveRecord::Base
  attr_accessible :currency_type_id, :nursery_id
  
  belongs_to :currency_type
  belongs_to :nursery
  
  validates :currency_type_id, presence:true
  validates :nursery_id, presence: true
end

app/models/currency_type.rb
# == Schema Information
#
# Table name: currency_types
#
#  id            :integer         not null, primary key
#  currency_name :string(255)
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#

class CurrencyType < ActiveRecord::Base
  attr_accessible :currency_name
  
  has_many :currencies
  
  validates :currency_name, presence: true
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  enable_authorization  
  
  def new
    @nursery = current_user.current_nursery
    @currency = @nursery.build_currency
  end
  
  def create
    @nursery = current_user.current_nursery
    @currency_type = CurrencyType.find_by_currency_name(params[:currency][:currency_type_id])
    @currency = @nursery.build_currency(currency_type_id: @currency_type.id)
    if @currency.save
      redirect_to currencies_path
      flash[:notice] = "Currency was added for nursery"
    else
      flash[:notice] = "Currency was not added to nursery"
      render :action => 'new'
    end
  end
  
  def edit
    @nursery = current_user.current_nursery
    @currency = Currency.find(params[:id])
  end
  
  def update
    @nursery = current_user.current_nursery
    @currency = Currency.find(params[:id])
    @currency_type = CurrencyType.find_by_currency_name(params[:currency][:currency_type_id])
    if @currency.update_attributes(currency_type_id: @currency_type.id)
      redirect_to currencies_path
      flash[:notice] = "Currency value was changed"
    else
      flash[:notice] = "Currency value was not changed"
      render :action => 'edit'
    end     
  end
  
  def index
    @nursery = current_user.current_nursery
    @currency = @nursery.currency
    @local_authority = @nursery.local_authority
    @top_tab = "Nursery Settings"
    @bottom_menu = "tab9" 
    @bottom_tab = 5    
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_currency_form.html.erb
<%= simple_form_for(@currency) do |currency_form| %>
	<%= currency_form.association :currency_type, collection: CurrencyType.all.map { |currency| currency.currency_name } %>
	<br />
	<br />
	<%= currency_form.button :submit, "Save" %>
<% end %>

app/views/currencies/edit.html.erb
<% provide(:title, 'Edit Currency') %>
<h1 class="inline-headline">Edit Currency</h1>
<br />
<br />
<%= simple_form_for(@currency) do |currency_form| %>
	<%= currency_form.association :currency_type, collection: CurrencyType.all.map { |currency| currency.currency_name }, selected: @currency.currency_type.currency_name %>
	<br />
	<br />
	<%= currency_form.button :submit, "Save" %>
<% end %>

app/views/currencies/index.html.erb
<% provide(:title, 'Nursery Defaults') %>
<h1 class="inline-headline">Defaults</h1>
<% unless @nursery.currency == nil %>
	<div class="add-button btn btn-info"><%= link_to "Edit", edit_currency_path(@currency) %></div>
	<br />
	<br />
	<div class="row">
		<div class="span2"><%= "#{'Nursery Name'}" %></div><div class="span6"><%= "#{@nursery.name}"	%></div><br /><br />
	</div>	
	<div class="row">
		<div class="span2"><%= "#{'Currency Type'}" %></div><div class="span6"><%= "#{@nursery.currency.currency_type.currency_name}" %></div><br /><br />
	</div>
<% else %>
	<div class="add-button btn btn-info"><%= link_to "Add Currency", new_currency_path %></div>
	<br /><br />
	<div class="row">
		<div class="span2"></div><div class="span6">There is no currency set for this nursery!</div>
	</div>
	<br /><br />
	<br /><br />
	<br /><br />
<% end %>
<div class="row">	
	<div class="span2"><%= "#{'Local Authority'}" %></div><div class="span6"><%= link_to "#{@local_authority.name}", local_authorities_path(local_authority: @local_authority)	%></div>
	<br /><br />
</div>

app/views/currencies/new.html.erb
<% provide(:title, 'Add Currency') %>
<h1 class="inline-headline">Add Currency</h1>
<br />
<br />
<%= render 'currency_form' %>