config/routes.rb
Kindsy::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :dashboards, :nursery_groups, :nurseries, :currencies, :rooms, :open_hours, :periods, :period_prices, :billing_periods, :presets, :discounts, :local_authorities, :terms

  resources :carers do
    member do
      get 'detail'
      get 'relationships'
      put 'remove_relationship'
      get 'search_children' 
      put 'add_children'
      put 'assign_accounts'
      get 'search_accounts'          
    end
  end 
  
  resources :accounts do
    member do
      get 'related_children'
      put 'remove_child'
      get 'search_children'
      put 'add_children'
      get 'related_carers'
      get 'search_carers'
      put 'add_carers'
      put 'remove_carer'
    end
  end
  
  resources :children do
    member do
      get 'detail'
    end
    resources :bookings
    resources :timesheets
  end
  
  resources :invoices do
    resources :invoice_line_items
  end
  
  get "static_pages/home"
  

  devise_for :users, :controllers => {:registrations => "registrations"}


  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  
  match '/static_pages_home' => "static_pages#home", as: :user_root


 
end

app/views/shared/_account_level_4_tabs.html.erb
<% @menu_items =  [["Summary", account_path(@account)], ["Related Children", related_children_account_path(@account)], ["Related Carers", related_carers_account_path(@account)]] %>
<% x = (0..2).to_a %>
<div class="tabbable tabs-left">
	<ul class="nav nav-tabs">
		<% x.each_with_index do |x| %>
			<li class=<%= 'active' if @menu_items[x][0] == @sidetab %>><a href=<%= @menu_items[x][1] %>><%= @menu_items[x][0] %></a> </li>
		<% end %>						
	</ul>
</div>	

app/views/shared/_carer_level_4_tabs.html.erb
<% @menu_items =  [["Summary", carer_path(@carer)], ["Personal Information", detail_carer_path(@carer)], ["Relationships", relationships_carer_path(@carer)], ["Bank Information", "#"], ["Regular Payments", "#"], ["Invoices", invoices_path(carer_id: @carer.id)], ["Payments Paid", "#"]] %>
<% x = (0..6).to_a %>
<div class="tabbable tabs-left">
	<ul class="nav nav-tabs">
		<% x.each_with_index do |x| %>
			<li class=<%= 'active' if @menu_items[x][0] == @sidetab %>><a href=<%= @menu_items[x][1] %>><%= @menu_items[x][0] %></a> </li>
		<% end %>						
	</ul>
</div>	

app/views/shared/_contact_info.html.erb
<%= contact_form.input :address_line_1, label: "Address 1" %>
<%= contact_form.input :address_line_2, label: "Address 2" %>
<%= contact_form.input :address_line_3, label: "Address 3" %>
<%= contact_form.input :town %>
<%= contact_form.input :county %>
<%= contact_form.input :post_code %>
<%= contact_form.input :telephone_1, label: "Primary Telephone" %>
<%= contact_form.input :email_1, label: "Primary Email" %>

app/views/shared/_error_messages.html.erb
<% if !alert.nil? || !notice.nil? %>
	<div id="error_explanation">
		<% if !notice.nil? %>
			<p class="notice alert-success"><%= notice %></p>
		<% else %>
			<p class="alert alert-error"><%= alert %></p>	
		<% end %>		
	</div>	
<% end %>

app/views/shared/_level_4_tabs.html.erb
<% @menu_items =  [["Summary", child_path(@child)], ["Personal", detail_child_path(@child)], ["Time & Attendance", child_bookings_path(@child)], ["Learning Journey", "#"], ["Finance", "#"], ["Notes", "#"]] %>
<% x = (0..5).to_a %>
<div class="tabbable tabs-left">
	<ul class="nav nav-tabs">
		<% x.each_with_index do |x| %>
			<li class=<%= 'active' if @menu_items[x][0] == @sidetab %>><a href=<%= @menu_items[x][1] %>><%= @menu_items[x][0] %></a> </li>
		<% end %>						
	</ul>
</div>	