config/routes.rb
Kindsy::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :dashboards, :nursery_groups, :nurseries, :currencies, :rooms, :open_hours, :periods, :period_prices, :billing_periods, :presets, :discounts, :local_authorities, :terms

  resources :carers do
    member do
      get 'detail'
      get 'relationships'
      put 'remove_relationship'
      get 'search_children' 
      put 'add_children'
      put 'assign_accounts'
      get 'search_accounts'          
    end
  end 
  
  resources :accounts do
    member do
      get 'related_children'
      put 'remove_child'
      get 'search_children'
      put 'add_children'
      get 'related_carers'
      get 'search_carers'
      put 'add_carers'
      put 'remove_carer'
    end
  end
  
  resources :children do
    member do
      get 'detail'
    end
    resources :bookings
    resources :timesheets
  end
  
  resources :invoices do
    resources :invoice_line_items
  end
  
  get "static_pages/home"
  

  devise_for :users, :controllers => {:registrations => "registrations"}


  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  
  match '/static_pages_home' => "static_pages#home", as: :user_root


 
end

app/models/nursery.rb
# == Schema Information
#
# Table name: nurseries
#
#  id                      :integer         not null, primary key
#  nursery_group_id        :integer
#  name                    :string(255)
#  created_at              :datetime        not null
#  updated_at              :datetime        not null
#  region_id               :integer
#  billing_cycle_start_day :integer
#  local_authority_id      :integer
#

class Nursery < ActiveRecord::Base
  attr_accessible :name, :region_id, :billing_cycle_start_day, :contact_info_attributes, :currency_attributes, :local_authority_id  

  belongs_to :nursery_group

  has_one :contact_info, :as => :addressable
  has_one :currency
  belongs_to :region
  belongs_to :local_authority
  
  has_many :accounts
  has_many :rooms
  has_many :staff_members
  has_many :children 
  has_many :carers
  has_many :open_hours
  has_many :periods
  has_many :presets
  has_many :bookings
  has_many :timesheets
  has_many :employments
  has_many :users, :through => :employments
  has_many :invoices  
  has_many :billing_periods
  has_many :discounts
  
  accepts_nested_attributes_for :contact_info
  accepts_nested_attributes_for :currency
  
  
  validates :nursery_group_id, presence: true, numericality: { only_integer: true }
  validates :name, presence: true
  validates :region_id, presence: true, numericality: { only_integer: true }
  validates :billing_cycle_start_day, presence: true, numericality: { only_integer: true }
  validates :local_authority_id, presence: true, numericality: { only_integer: true }


end

app/controllers/nurseries_controller.rb
class NurseriesController < ApplicationController
  enable_authorization

  def index
    @group = NurseryGroup.first
    @nurseries = @group.nurseries
    @top_tab = "Group Settings"
    @bottom_menu = "tab10" 
    @bottom_tab = 1
  end
  
  def show
    @nursery = Nursery.find(params[:id])
    @top_tab = "Nursery Settings"
    @bottom_menu = "tab9" 
    @bottom_tab = 1    
  end
  
  def new
    @group = NurseryGroup.first
    @nursery = @group.nurseries.build
    @contact_info = @nursery.build_contact_info  
    @top_tab = "Group Settings"
    @bottom_menu = "tab10" 
    @bottom_tab = 1          
  end
  
  def create
    @group = NurseryGroup.first
    @nursery = @group.nurseries.build(params[:nursery]) 
    if @nursery.save
      redirect_to nurseries_path
      flash[:notice] = "New nursery was added!"      
    else
      flash[:notice] = "Nursery addition failed!"
      render :action => 'new'
    end
  end
  
  def edit
    @nursery = Nursery.find(params[:id])
    @top_tab = "Group Settings"
    @bottom_menu = "tab10" 
    @bottom_tab = 1     
  end
  
  def update
    @nursery = Nursery.find(params[:id])
    if @nursery.update_attributes(params[:nursery])
      redirect_to nurseries_path
      flash[:notice] = "Nursery was updated!"  
    else
      flash[:notice] = "Nursery update failed!"
      render :action => 'edit'
    end
  end
end

app/helpers/nurseries_helper.rb
module NurseriesHelper
end

app/views/nurseries/_nursery.html.erb
<%= simple_form_for(@nursery) do |nursery_form| %>
	<%= nursery_form.input :name, label: "Nursery Name" %>
	<%= nursery_form.association :region %>
	<%= nursery_form.association :local_authority %>
	<%= nursery_form.input :billing_cycle_start_day, label: "Billing Cycle Start Day" %>
	<%= nursery_form.simple_fields_for :contact_info do |contact_form| %>
		<%= render 'shared/contact_info', :contact_form => contact_form %>
	<% end %>
	<%= nursery_form.button :submit, "Save" %>
<% end %>

app/views/nurseries/edit.html.erb
<% provide(:title, "Edit this nursery") %>
<h1 class="inline-headline">Edit this nursery</h1><br /><br />
<%= render 'nursery' %>

app/views/nurseries/index.html.erb
<% provide(:title, 'Nursery List') %>
<h1 class="inline-headline">Our Nurseries</h1>
<div class="add-button btn btn-success"><%= link_to "+ Add Nursery", new_nursery_path %></div>
<br />
<br />
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Nursery Name</th>
			<th>Region</th>
			<th>Town</th>
			<th>Postcode</th>
			<th>...</th>
		</tr>
	</thead>
	<tbody>
		<% @nurseries.each do |nursery| %>
			<tr>
				<td><%= nursery.name %></td>
				<td><%= nursery.region.name %></td>
				<td><%= nursery.contact_info.town %></td>
				<td><%= nursery.contact_info.post_code %></td>
				<td><%= link_to '...', nursery_path(nursery.id), :title => "View" %>&nbsp;&nbsp;<%= link_to raw('<i class="icon-pencil icon-large"></i>'), edit_nursery_path(nursery.id), :title => "Edit" %></td>				
			</tr>

		<% end %>		
	</tbody>	
</table>
<p>

</p>

app/views/nurseries/new.html.erb
<% provide(:title, "Add a nursery") %>
<h1 class="inline-headline">Add a nursery</h1><br /><br />
<%= render 'nursery' %>

app/views/nurseries/show.html.erb
<% provide(:title, 'Nursery Contact Info')%>
<h1 class="inline-headline">Contact Information</h1>
<div class="add-button btn btn-info"><%= link_to "Edit", edit_nursery_path(@nursery) %></div>
<br />
<br />
<div class="row">
	<div class="span2"><%= "#{'Nursery Name'}" %></div><div class="span6"><%= "#{@nursery.name}"	%></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'Address 1'}" %></div><div class="span6"><%= "#{@nursery.contact_info.address_line_1}" %></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'Address 2'}" %></div><div class="span6"><%= "#{@nursery.contact_info.address_line_2}" %></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'Address 3'}" %></div><div class="span6"><%= "#{@nursery.contact_info.address_line_3}" %></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'Town'}" %></div><div class="span6"><%= "#{@nursery.contact_info.town}" %></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'County'}" %></div><div class="span6"><%= "#{@nursery.contact_info.county}" %></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'Post code'}" %></div><div class="span6"><%= "#{@nursery.contact_info.post_code}" %></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'Primary Telephone'}" %></div><div class="span6"><%= "#{@nursery.contact_info.telephone_1}" %></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'Primary Email'}" %></div><div class="span6"><%= " #{@nursery.contact_info.email_1}" %></div><br />
</div>
<br />
<br />