config/routes.rb
Kindsy::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :dashboards, :nursery_groups, :nurseries, :currencies, :rooms, :open_hours, :periods, :period_prices, :billing_periods, :presets, :discounts, :local_authorities, :terms

  resources :carers do
    member do
      get 'detail'
      get 'relationships'
      put 'remove_relationship'
      get 'search_children' 
      put 'add_children'
      put 'assign_accounts'
      get 'search_accounts'          
    end
  end 
  
  resources :accounts do
    member do
      get 'related_children'
      put 'remove_child'
      get 'search_children'
      put 'add_children'
      get 'related_carers'
      get 'search_carers'
      put 'add_carers'
      put 'remove_carer'
    end
  end
  
  resources :children do
    member do
      get 'detail'
    end
    resources :bookings
    resources :timesheets
  end
  
  resources :invoices do
    resources :invoice_line_items
  end
  
  get "static_pages/home"
  

  devise_for :users, :controllers => {:registrations => "registrations"}


  devise_scope :user do
    root :to => 'devise/sessions#new'
  end
  
  match '/static_pages_home' => "static_pages#home", as: :user_root


 
end

app/models/open_hour.rb
# == Schema Information
#
# Table name: open_hours
#
#  id          :integer         not null, primary key
#  nursery_id  :integer
#  day_of_week :string(255)
#  open_time   :time
#  close_time  :time
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class OpenHour < ActiveRecord::Base
  attr_accessible :close_time, :day_of_week, :nursery_id, :open_time

  belongs_to :nursery
  

  validates :nursery_id, presence: true
  validates :day_of_week, presence: true
  validates :open_time, presence: true
  validates :close_time, presence: true
  
end

app/controllers/open_hours_controller.rb
class OpenHoursController < ApplicationController
  enable_authorization

  def new
    @nursery = current_user.current_nursery
    @open_hours = @nursery.open_hours.build
    @top_tab = "Nursery Settings"
    @bottom_menu = "tab9" 
    @bottom_tab = 4    
  end
  
  def create
    @nursery = current_user.current_nursery
    @open_hours = @nursery.open_hours.build(params[:open_hour])
    if @open_hours.save
      redirect_to open_hours_path
      flash[:notice] = "Open Hours were added for the nursery"
    else
      flash[:notice] = "Open Hours were not added for the nursery"
      render :action => 'new'
    end
  end
  
  def edit
    @nursery = current_user.current_nursery
    @open_hours = OpenHour.find(params[:id])
    @top_tab = "Nursery Settings"
    @bottom_menu = "tab9" 
    @bottom_tab = 4    
  end
  
  def update
    @nursery = current_user.current_nursery
    @open_hours = OpenHour.find(params[:id])
    if @open_hours.update_attributes(params[:open_hour])
      redirect_to open_hours_path
      flash[:notice] = "Nursery Open Hours were changed"
    else
      flash[:notice] = "Nursery Open Hours were not changed"
      render :action => 'edit'
    end
  end
  
  def index
    @nursery = current_user.current_nursery
    @open_hours = @nursery.open_hours
    @open_days = @open_hours.map { |a| a.day_of_week }
    @top_tab = "Nursery Settings"
    @bottom_menu = "tab9" 
    @bottom_tab = 4    
  end
  
  def destroy
    @nursery = current_user.current_nursery
    OpenHour.find(params[:id]).destroy
    flash[:success] = "Nursery Open Hours record deleted"
    redirect_to open_hours_path
  end
  
  def show
    @nursery = current_user.current_nursery
    @open_hours = OpenHour.find(params[:id])
    @top_tab = "Nursery Settings"
    @bottom_menu = "tab9" 
    @bottom_tab = 4      
  end
  
end

app/helpers/open_hours_helper.rb
module OpenHoursHelper
end

app/views/open_hours/_open_buttons.html.erb
<% if @open_days.include?("Sunday") %>
	<div class="open-hours-button btn btn-success"><%= link_to "S", open_hour_path(@open_hours[@open_days.index("Sunday")].id), :title => "Delete",  method: :delete, data: {confirm: "You sure?"} %></div>
<% else %>
	<div class="no-open-hours-button btn"><%= link_to "S", new_open_hour_url(params.merge(:day_of_week =>"Sunday")) %></div>
<% end %>
<% if @open_days.include?("Monday") %>
	<div class="open-hours-button btn btn-success"><%= link_to "M", open_hour_path(@open_hours[@open_days.index("Monday")].id), :title => "Delete",  method: :delete, data: {confirm: "You sure?"} %></div>
<% else %>
	<div class="no-open-hours-button btn"><%= link_to "M", new_open_hour_url(params.merge(:day_of_week =>"Monday")) %></div>
<% end %>
<% if @open_days.include?("Tuesday") %>
	<div class="open-hours-button btn btn-success"><%= link_to "T", open_hour_path(@open_hours[@open_days.index("Tuesday")].id), :title => "Delete",  method: :delete, data: {confirm: "You sure?"} %></div>
<% else %>
	<div class="no-open-hours-button btn"><%= link_to "T", new_open_hour_url(params.merge(:day_of_week =>"Tuesday")) %></div>
<% end %>
<% if @open_days.include?("Wednesday") %>
	<div class="open-hours-button btn btn-success"><%= link_to "W", open_hour_path(@open_hours[@open_days.index("Wednesday")].id), :title => "Delete",  method: :delete, data: {confirm: "You sure?"} %></div>
<% else %>
	<div class="no-open-hours-button btn"><%= link_to "W", new_open_hour_url(params.merge(:day_of_week =>"Wednesday")) %></div>
<% end %>
<% if @open_days.include?("Thursday") %>
	<div class="open-hours-button btn btn-success"><%= link_to "T", open_hour_path(@open_hours[@open_days.index("Thursday")].id), :title => "Delete",  method: :delete, data: {confirm: "You sure?"} %></div>
<% else %>
	<div class="no-open-hours-button btn"><%= link_to "T", new_open_hour_url(params.merge(:day_of_week =>"Thursday")) %></div>
<% end %>
<% if @open_days.include?("Friday") %>
	<div class="open-hours-button btn btn-success"><%= link_to "F", open_hour_path(@open_hours[@open_days.index("Friday")].id), :title => "Delete",  method: :delete, data: {confirm: "You sure?"} %></div>
<% else %>
	<div class="no-open-hours-button btn"><%= link_to "F", new_open_hour_url(params.merge(:day_of_week =>"Friday")) %></div>
<% end %>
<% if @open_days.include?("Saturday") %>
	<div class="open-hours-button btn btn-success"><%= link_to "S", open_hour_path(@open_hours[@open_days.index("Saturday")].id), :title => "Delete",  method: :delete, data: {confirm: "You sure?"} %></div>
<% else %>
	<div class="no-open-hours-button btn"><%= link_to "S", new_open_hour_url(params.merge(:day_of_week =>"Saturday")) %></div>
<% end %>

app/views/open_hours/_open_hour.html.erb
<%= simple_form_for(@open_hours) do |open_hour_form| %>
	<%= open_hour_form.input :day_of_week, collection: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], :selected => (params[:day_of_week])  %>
	<%= open_hour_form.input :open_time, label: "Open Time" %>
	<%= open_hour_form.input :close_time, label: "Close Time" %>
	<%= open_hour_form.button :submit, "Save" %>
<% end %>

app/views/open_hours/edit.html.erb
<% provide(:title, 'Edit Nursery Open Hours') %>
<h1 class="inline-headline">Edit Nursery Open Hours</h1>
<br />
<br />
<%= render 'open_hour' %>

app/views/open_hours/index.html.erb
<% provide(:title, 'Nursery Opening Times') %>
<h1 class="inline-headline">Opening Times</h1>
<br />
<br />
<br />
<h3 class="inline-headline">General Opening Times</h3>
<br />
<br />
Opening Days
<%= render 'open_buttons' %>
<br />
<br />
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Day</th>
			<th>Time Range</th>
			<th>...</th>
		</tr>
	</thead>
	<tbody>
		<% @open_hours.each do |open_hour| %>
			<tr>
				<td><%= open_hour.day_of_week %></td>
				<td><%= "#{open_hour.open_time.strftime("%I:%M %P")} #{'-'} #{open_hour.close_time.strftime("%I:%M %P")}" %></td>
				<td><%= link_to '...', open_hour_path(open_hour.id ), :title => "View" %>&nbsp;&nbsp;<%= link_to raw('<i class="icon-pencil icon-large"></i>'), edit_open_hour_path(open_hour.id, params.merge(:day_of_week => open_hour.day_of_week)), :title => "Edit" %></td>				
			</tr>
		<% end %>		
	</tbody>		
</table>

app/views/open_hours/new.html.erb
<% provide(:title, 'Add Open Hours') %>
<h1 class="inline-headline">Add Nursery Open Hours</h1>
<br />
<br />
<%= render 'open_hour' %>

app/views/open_hours/show.html.erb
<% provide(:title, 'Nursery Open Hours') %>
<h1 class="inline-headline">Nursery Open Hours</h1>
<div class="add-button btn btn-info"><%= link_to "Edit", edit_open_hour_path(@open_hours, params.merge(:day_of_week => @open_hours.day_of_week)) %></div>
<br />
<br />
<div class="row">
	<div class="span2"><%= "#{'Day'}" %></div><div class="span6"><%= "#{@open_hours.day_of_week}"	%></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'Open Time'}" %></div><div class="span6"><%= "#{@open_hours.open_time.strftime("%I:%M %P")}" %></div><br /><br />
</div>
<div class="row">
	<div class="span2"><%= "#{'Close Time'}" %></div><div class="span6"><%= "#{@open_hours.close_time.strftime("%I:%M %P")}" %></div><br /><br />
</div>